/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './my-component.module';
import * as import2 from '@angular/core/src/di/injector';
class MyComponentModuleInjector extends import0.NgModuleInjector<import1.MyComponentModule> {
  _MyComponentModule_0:import1.MyComponentModule;
  constructor(parent:import2.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  createInternal():import1.MyComponentModule {
    this._MyComponentModule_0 = new import1.MyComponentModule();
    return this._MyComponentModule_0;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import1.MyComponentModule)) { return this._MyComponentModule_0; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const MyComponentModuleNgFactory:import0.NgModuleFactory<import1.MyComponentModule> = new import0.NgModuleFactory(MyComponentModuleInjector,import1.MyComponentModule);